### ISSUE TITLE
Failed to download for macOS

### ISSUE THREAD

**Issue by Dentrax** [konradsz/igrep#27] opened 2022-08-16 07:34 UTC
It seems the download link is broken.

```bash
$ brew tap konradsz/igrep https://github.com/konradsz/igrep.git
$ brew install igrep

Running `brew update --auto-update`...
==> Downloading https://github.com/konradsz/igrep/releases/download/v0.5.1/igrep-v0.5.1-x86_64-apple-darwin.tar.gz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/240747715/522d8b04-1b53-4801-a18c-12333b2d
curl: (22) The requested URL returned error: 401                     #  #  ##

Error: igrep: Failed to download resource "igrep"
Download failed: https://github.com/konradsz/igrep/releases/download/v0.5.1/igrep-v0.5.1-x86_64-apple-darwin.tar.gz
```

**Comment by konradsz** [comment] 2022-08-16 21:09
Hi,
url https://github.com/konradsz/igrep/releases/download/v0.5.1/igrep-v0.5.1-x86_64-apple-darwin.tar.gz is correct (you can verify by downloading via browser), `brew` does not complain on my machine. Please check again - either it was temporary github hiccup or the problem is with your network (proxy?)

**Comment by konradsz** [comment] 2022-08-28 19:58
Hi,
I am closing this issue as there is nothing I can do to help you.

**Closed by konradsz** 2022-08-28 19:58 UTC
